title: Simranjeet Kaur Gill
description: Analytically driven, currently advancing my expertise through a Master's in Information Technology Management to harness data and technology for strategic decision-making 
site_title: '@skg - Simranjeet Kaur Gill'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SimranjeetG
Linkedin_url: https://www.linkedin.com/in/simranjeet-kaur-gill-6106aa234/
email: simranjeetkaur9340@gmail.com
#keybase_username: 
##twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
# google_analytics: 